services:
  db:
    platform: linux/x86_64
    image: postgis/postgis:14-3.4-alpine
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
